export const SET_PLAYER = "SET_PLAYER"
export const UNSET_PLAYER = "UNSET_PLAYER"
export const PUNCH_FROM_ENEMY_PLAYER_TO_PLAYER = 'PUNCH_FROM_ENEMY_PLAYER_TO_PLAYER'
export const PUNCH_FROM_MOB_TO_PLAYER = 'PUNCH_FROM_MOB_TO_PLAYER'
export const REGENERATE = 'REGENERATE'
